-- auto Generated on 2021-01-24
-- DROP TABLE IF EXISTS `role`;
CREATE TABLE `role`(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	detail VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'detail',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role';
